{{- if and .Values.admin .Values.bfl.username (eq .Values.admin .Values.bfl.username) }}
{{- $ollamaclientDomainENV := split "," .Values.domain.ollamaclient -}}
{{- $ollamaclientDomain := index $ollamaclientDomainENV "_0" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - name: api
          image: "docker.io/beclab/harveyff-olares-ollama:v0.1.8"
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: DISPLAY
              value: ":0"
            - name: OLLAMA_MODEL
              valueFrom:
                configMapKeyRef:
                  name: ollama-env
                  key: MODEL_NAME
            - name: OLLAMA_URL
              value: "http://ollama.ollamabgem3567mv2server-shared:11434"
            - name: APP_URL
              value: "https://{{ $ollamaclientDomain }}"
            - name: OLLAMA_NOPRUNE
              value: "1"
          resources:
            requests:
              cpu: 300m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - name: "api"
      port: 8081
      targetPort: 8080
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: sharedentrances-api
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - name: "api"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
{{- end }}
